/**
 * Author:J
 * Describe: 路由Constants
 */
export class NavName {
  static readonly MAIN_PAGE = 'mainPage' //主页面
  static readonly SPLASH_PAGE = 'splashPage' //启动页面
  static readonly LOGIN_VIEW = 'loginView' //登录页面
  // static readonly HOME_VIEW = 'homeView' //首页
  // static readonly QUESTION_VIEW = 'questionView' //问答页面
  // static readonly SCHEME_VIEW = 'schemeView' //体系页面
  // static readonly MINE_VIEW = 'mineView' //我的页面
}
